[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
colored = "2.0.0"
wasmtime = { workspace = true }
wasmtime-wasi = "22.0.0"
wat-annotator = { path = "../wat-annotator" }
