[package]
name = "example-component"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.27.0", features = ["bitflags"] }

[package.metadata.component]
package = "component:example-component"

[package.metadata.component.dependencies]
